// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdyyeygvfojnebppxyug.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkeXlleWd2Zm9qbmVicHB4eXVnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MTUzOTMsImV4cCI6MjA2MzM5MTM5M30.yxmHcp5mAyHj5lGbCBN7mBrnVPcfHDkSJvd4-G3EoD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);